#! /bin/sh
# preinst script for xymon

set -e

# Workaround for http://bugs.debian.org/560317 in case debconf is too old like on Squeeze
export DPKG_MAINTSCRIPT_PACKAGE=${DPKG_MAINTSCRIPT_PACKAGE:-xymon}
export DPKG_MAINTSCRIPT_NAME=${DPKG_MAINTSCRIPT_NAME:-preinst}

case "$1" in
    install|upgrade)
	# stop the client when the server is installed
	invoke-rc.d --quiet hobbit-client stop || true
	invoke-rc.d xymon-client stop || true
	if test "$2" && dpkg --compare-versions "$2" lt 4.3.7-1~~ &&
			test -d /var/lib/hobbit/www ; then
		# we want to replace symlinks with directories, prod dpkg to do it
		move_link () {
			test -h "$1" || return
			test -d "$1" && return
			test -e "$1.dpkg-old" && return
			mv "$1" "$1.dpkg-old"
		}
		cd /var/lib/hobbit/www
		move_link menu
	fi
	;;
esac

#DEBHELPER#

exit 0
